application: twitter-timeline-app 
version: 2
runtime: python27
threadsafe: true
api_version: 1

handlers:
# Route handlers
- url: /app
  static_dir: static 
- url: .*
  script: api.app


libraries:
- name: webapp2
  version: latest
